<template>

<pre style="background-color: var(--term-bg); color: var(--term-fg)">[<span style="color: var(--term-6)">user</span>@<span style="color: var(--term-1)">hostname</span> <span style="color: var(--term-2)">~</span>]$ ./rows.sh
     <span style="color: var(--term-0)">┌──────────────────────────────────────────────────────────────────────────┐
</span><span style="color: var(--term-7)"> DFT </span><span style="color: var(--term-0)">│   black  </span><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="color: var(--term-8)">  black  </span><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> BLK </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-0)">  black  </span></span><span style="background-color: var(--term-0)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-0)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-0)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> RED </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-1)">  black  </span></span><span style="background-color: var(--term-1)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-1)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-1)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> GRN </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-2)">  black  </span></span><span style="background-color: var(--term-2)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-2)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-2)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> YEL </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-3)">  black  </span></span><span style="background-color: var(--term-3)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-3)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-3)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> BLU </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-4)">  black  </span></span><span style="background-color: var(--term-4)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-4)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-4)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> MAG </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-5)">  black  </span></span><span style="background-color: var(--term-5)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-5)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-5)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> CYN </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-6)">  black  </span></span><span style="background-color: var(--term-6)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-6)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-6)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-7)"> WHT </span><span style="color: var(--term-0)">│ <span style="background-color: var(--term-7)">  black  </span></span><span style="background-color: var(--term-7)"><span style="color: var(--term-1)">   red   </span><span style="color: var(--term-2)">  green  </span><span style="color: var(--term-3)">  yellow </span><span style="color: var(--term-4)">   blue  </span><span style="color: var(--term-5)"> magenta </span><span style="color: var(--term-6)">   cyan  </span><span style="color: var(--term-7)">  white  </span></span><span style="color: var(--term-0)"> │
</span>     <span style="color: var(--term-0)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-7)"><span style="color: var(--term-8)">  black  </span></span><span style="background-color: var(--term-7)"><span style="color: var(--term-9)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-0)">│
</span>     <span style="color: var(--term-0)">└──────────────────────────────────────────────────────────────────────────┘
</span>[<span style="color: var(--term-6)">user</span>@<span style="color: var(--term-1)">hostname</span> <span style="color: var(--term-2)">~</span>]$ ls -l
total 8
drwxr-xr-x 2 user user 4096 Aug  7 20:55 <span style="color: var(--term-12); font-weight: bold; ">dir</span>
-rwxr-xr-x 1 user user    0 Aug  7 20:55 <span style="color: var(--term-10) ; font-weight: bold;">executable</span>
prw-r--r-- 1 user user    0 Aug  7 20:56 <span style="color: var(--term-3)">fifo</span>
lrwxrwxrwx 1 user user    7 Aug  7 20:55 <span style="color: var(--term-14) ; font-weight: bold;">link</span> -> regular
drwxr-xrwx 2 user user 4096 Aug  7 20:55 <span style="color: var(--term-4); background-color: var(--term-2)">other_writable</span>
-rw-r--r-- 1 user user    0 Aug  7 20:55 regular
srwxr-xr-x 1 user user    0 Aug  7 21:07 <span style="color: var(--term-13) ; font-weight: bold;">socket</span>
[<span style="color: var(--term-6)">user</span>@<span style="color: var(--term-1)">hostname</span> <span style="color: var(--term-2)">~</span>]$ <span style="color: var(--term-cursor)" class="blink">█</span>
</pre>


</template>

<style scoped>

.blink {
  animation: 0.5s step-end alternate infinite both blink;
}

@keyframes blink {
  0% {
    opacity: 100%;
  }
  50% {
    opacity: 0%;
  }
  100% {
    opacity: 0%;
  }
}

</style>