<template>

<pre style="background-color: var(--term-light-bg); color: var(--term-light-fg)">[<span style="color: var(--term-light-06)">user</span>@<span style="color: var(--term-light-01)">hostname</span> <span style="color: var(--term-light-02)">~</span>]$ ./rows.sh
     <span style="color: var(--term-light-00)">┌──────────────────────────────────────────────────────────────────────────┐
</span><span style="color: var(--term-light-07)"> DFT </span><span style="color: var(--term-light-00)">│   black  </span><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="color: var(--term-light-08)">  black  </span><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> BLK </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-00)">  black  </span></span><span style="background-color: var(--term-light-00)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-00)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-00)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> RED </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-01)">  black  </span></span><span style="background-color: var(--term-light-01)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-01)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-01)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> GRN </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-02)">  black  </span></span><span style="background-color: var(--term-light-02)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-02)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-02)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> YEL </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-03)">  black  </span></span><span style="background-color: var(--term-light-03)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-03)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-03)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> BLU </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-04)">  black  </span></span><span style="background-color: var(--term-light-04)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-04)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-04)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> MAG </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-05)">  black  </span></span><span style="background-color: var(--term-light-05)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-05)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-05)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> CYN </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-06)">  black  </span></span><span style="background-color: var(--term-light-06)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-06)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-06)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-light-07)"> WHT </span><span style="color: var(--term-light-00)">│ <span style="background-color: var(--term-light-07)">  black  </span></span><span style="background-color: var(--term-light-07)"><span style="color: var(--term-light-01)">   red   </span><span style="color: var(--term-light-02)">  green  </span><span style="color: var(--term-light-03)">  yellow </span><span style="color: var(--term-light-04)">   blue  </span><span style="color: var(--term-light-05)"> magenta </span><span style="color: var(--term-light-06)">   cyan  </span><span style="color: var(--term-light-07)">  white  </span></span><span style="color: var(--term-light-00)"> │
</span>     <span style="color: var(--term-light-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-light-07)"><span style="color: var(--term-light-08)">  black  </span></span><span style="background-color: var(--term-light-07)"><span style="color: var(--term-light-09)">   red   </span><span style="color: var(--term-light-10)">  green  </span><span style="color: var(--term-light-11)">  yellow </span><span style="color: var(--term-light-12)">   blue  </span><span style="color: var(--term-light-13)"> magenta </span><span style="color: var(--term-light-14)">   cyan  </span><span style="color: var(--term-light-15)">  white  </span></span></span> <span style="color: var(--term-light-00)">│
</span>     <span style="color: var(--term-light-00)">└──────────────────────────────────────────────────────────────────────────┘
</span>[<span style="color: var(--term-light-06)">user</span>@<span style="color: var(--term-light-01)">hostname</span> <span style="color: var(--term-light-02)">~</span>]$ ls -l
total 8
drwxr-xr-x 2 user user 4096 Aug  7 20:55 <span style="color: var(--term-light-12); font-weight: bold; ">dir</span>
-rwxr-xr-x 1 user user    0 Aug  7 20:55 <span style="color: var(--term-light-10) ; font-weight: bold;">executable</span>
prw-r--r-- 1 user user    0 Aug  7 20:56 <span style="color: var(--term-light-03)">fifo</span>
lrwxrwxrwx 1 user user    7 Aug  7 20:55 <span style="color: var(--term-light-14) ; font-weight: bold;">link</span> -> regular
drwxr-xrwx 2 user user 4096 Aug  7 20:55 <span style="color: var(--term-light-04); background-color: var(--term-light-02)">other_writable</span>
-rw-r--r-- 1 user user    0 Aug  7 20:55 regular
srwxr-xr-x 1 user user    0 Aug  7 21:07 <span style="color: var(--term-light-13) ; font-weight: bold;">socket</span>
[<span style="color: var(--term-light-06)">user</span>@<span style="color: var(--term-light-01)">hostname</span> <span style="color: var(--term-light-02)">~</span>]$ <span style="color: var(--term-light-cursor)" class="blink">█</span>
</pre>


</template>

<style scoped>

.blink {
  animation: 0.5s step-end alternate infinite both blink;
}

@keyframes blink {
  0% {
    opacity: 100%;
  }
  50% {
    opacity: 0%;
  }
  100% {
    opacity: 0%;
  }
}

</style>