<template>

<pre style="background-color: var(--term-bg); color: var(--term-fg)">[<span style="color: var(--term-06)">user</span>@<span style="color: var(--term-01)">hostname</span> <span style="color: var(--term-02)">~</span>]$ ./rows.sh
     <span style="color: var(--term-00)">┌──────────────────────────────────────────────────────────────────────────┐
</span><span style="color: var(--term-07)"> DFT </span><span style="color: var(--term-00)">│   black  </span><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="color: var(--term-08)">  black  </span><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> BLK </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-00)">  black  </span></span><span style="background-color: var(--term-00)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-00)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-00)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> RED </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-01)">  black  </span></span><span style="background-color: var(--term-01)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-01)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-01)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> GRN </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-02)">  black  </span></span><span style="background-color: var(--term-02)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-02)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-02)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> YEL </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-03)">  black  </span></span><span style="background-color: var(--term-03)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-03)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-03)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> BLU </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-04)">  black  </span></span><span style="background-color: var(--term-04)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-04)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-04)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> MAG </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-05)">  black  </span></span><span style="background-color: var(--term-05)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-05)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-05)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> CYN </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-06)">  black  </span></span><span style="background-color: var(--term-06)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-06)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-06)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">├──────────────────────────────────────────────────────────────────────────┤
</span><span style="color: var(--term-07)"> WHT </span><span style="color: var(--term-00)">│ <span style="background-color: var(--term-07)">  black  </span></span><span style="background-color: var(--term-07)"><span style="color: var(--term-01)">   red   </span><span style="color: var(--term-02)">  green  </span><span style="color: var(--term-03)">  yellow </span><span style="color: var(--term-04)">   blue  </span><span style="color: var(--term-05)"> magenta </span><span style="color: var(--term-06)">   cyan  </span><span style="color: var(--term-07)">  white  </span></span><span style="color: var(--term-00)"> │
</span>     <span style="color: var(--term-00)">│</span> <span style="font-weight: bold;"><span style="background-color: var(--term-07)"><span style="color: var(--term-08)">  black  </span></span><span style="background-color: var(--term-07)"><span style="color: var(--term-09)">   red   </span><span style="color: var(--term-10)">  green  </span><span style="color: var(--term-11)">  yellow </span><span style="color: var(--term-12)">   blue  </span><span style="color: var(--term-13)"> magenta </span><span style="color: var(--term-14)">   cyan  </span><span style="color: var(--term-15)">  white  </span></span></span> <span style="color: var(--term-00)">│
</span>     <span style="color: var(--term-00)">└──────────────────────────────────────────────────────────────────────────┘
</span>[<span style="color: var(--term-06)">user</span>@<span style="color: var(--term-01)">hostname</span> <span style="color: var(--term-02)">~</span>]$ ls -l
total 8
drwxr-xr-x 2 user user 4096 Aug  7 20:55 <span style="color: var(--term-12); font-weight: bold; ">dir</span>
-rwxr-xr-x 1 user user    0 Aug  7 20:55 <span style="color: var(--term-10) ; font-weight: bold;">executable</span>
prw-r--r-- 1 user user    0 Aug  7 20:56 <span style="color: var(--term-03)">fifo</span>
lrwxrwxrwx 1 user user    7 Aug  7 20:55 <span style="color: var(--term-14) ; font-weight: bold;">link</span> -> regular
drwxr-xrwx 2 user user 4096 Aug  7 20:55 <span style="color: var(--term-04); background-color: var(--term-02)">other_writable</span>
-rw-r--r-- 1 user user    0 Aug  7 20:55 regular
srwxr-xr-x 1 user user    0 Aug  7 21:07 <span style="color: var(--term-13) ; font-weight: bold;">socket</span>
[<span style="color: var(--term-06)">user</span>@<span style="color: var(--term-01)">hostname</span> <span style="color: var(--term-02)">~</span>]$ <span style="color: var(--term-cursor)" class="blink">█</span>
</pre>


</template>

<style scoped>

.blink {
  animation: 0.5s step-end alternate infinite both blink;
}

@keyframes blink {
  0% {
    opacity: 100%;
  }
  50% {
    opacity: 0%;
  }
  100% {
    opacity: 0%;
  }
}

</style>